import Logo from "./components/Logo";
import Navigation from "./components/Navigation";
import "./globals.css";
export const metadata = {
  title: "Hotel Management",
  // description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header>
          <Logo />
          <Navigation />
        </header>
        <main>{children}</main>
        <footer>
          <p>© 2023 Hotel Management. All rights reserved.</p>
        </footer>
      </body>
    </html>
  );
}
